import classes from "./show-traditions.module.css";
import SortTraditions from "./sort-traditions";
import Traditions from "./traditions";
import Filter from "../ui/filter";
import Modal from "../ui/modal";
import Links from "../header/links-and-logo/links";
import { useState } from "react";
import { useGetSummaryTree } from "../../api/hooks/allHooks";
import { useSelector } from "react-redux";
import { extractText, extractTreeIndex } from "../../utils/manipulation";
